#!/usr/bin/env bash
. functions/ssh
. functions/hosts

if [ -z "${1}" ]; then
  echo "You're doing it wrong"
  exit 1
fi

if ! HOST_IP=$(get_ip "${1}"); then
  echo "Error getting ip: ${HOST_IP}"
  exit 1
fi

ping_ssh "${HOST_IP}"

if [ "${2}" = "copy" ]; then
  scp root@"${HOST_IP}":/etc/rancher/rke2/rke2.yaml "${1}".yaml
  sed -i "s/127.0.0.1/${HOST_IP}/g" "${1}".yaml
  exit 0
fi

if [ "${2}" = "copy-token" ]; then
  mkdir -p extra_files
  scp root@"${HOST_IP}":/var/lib/rancher/rke2/server/node-token extra_files/join.token
  exit 0
fi

nix run github:nix-community/nixos-anywhere -- --flake .#"${1}" --extra-files ./extra_files wonko@"${HOST_IP}"
