#!/usr/bin/env bash

./deploy master1
echo -n "Press enter when node is up"
read -r

./deploy master1 copy
./deploy master1 copy-token

ADDITIONAL_NODES=('master2' 'master3' 'worker1' 'worker2' 'worker3')

for node in "${ADDITIONAL_NODES[@]}"; do
  echo ./deploy "${node}"
done
