apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rke2-argocd
  namespace: kube-system
spec:
  targetNamespace: argocd
  createNamespace: true
  version: @version@
  chart: argo-cd
  repo: https://argoproj.github.io/argo-helm
  valuesContent: |-
    global:
      domain: argocd.4amlunch.net
      logging:
        format: json
      networkPolicy:
        create: true
    configs:
      cm:
        dex.config: |
          connectors:
            - type: github
              id: github
              name: GitHub
              config:
                clientID: REDACTED
                clientSecret: REDACTED
                orgs:
                  - name: 4amlunch
      params:
        server.insecure: true
      rbac:
        policy.csv: |
          g, 4amlunch:admin, role:org-admin
          p, role:org-admin, applications, *, */*, allow
          p, role:org-admin, clusters, get, *, allow
          p, role:org-admin, repositories, *, *, allow
          p, role:org-admin, logs, get, *, allow
          p, role:org-admin, exec, create, */*, allow
    controller:
      replicas: 1
    redis-ha:
      enabled: true
    server:
      replicas: 2
    repoServer:
      replicas: 2
    applicationSet:
      replicas: 2
