apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    cluster:
      name: @clusterName@
    kubeProxyReplacement: strict
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 6443
    hubble:
      enabled: @hubbleEnabled@
      relay:
        enabled: @hubbleRelay@
      ui:
        enabled: @hubbleUI@
    gatewayAPI:
      enabled: @gatewayAPI@
    ipv4NativeRoutingCIDR: @privateCIDR@
    routingMode: native
    enableIPv4Masquerade: true
    autoDirectNodeRoutes: true
    devices: @publicNIC@ @privateNIC@
    nodePort:
      directRoutingDevice: @privateNIC@
    envoy:
      enabled: true
    annotateK8sNode: true
    monitor:
      enabled: true
    prometheus:
      enabled: true
    bpf:
      masquerade: true
      vlanBypass: @vlanID@
    ipMasqAgent:
      enabled: true
      config:
        nonMasqueradeCIDRs:
          - @privateCIDR@