apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rke2-cert-manager
  namespace: kube-system
spec:
  targetNamespace: cert-manager
  createNamespace: true
  version: @version@
  chart: cert-manager
  repo: https://charts.jetstack.io
  valuesContent: |-
    crds:
      enabled: true
      keep: true
