apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    kubeProxyReplacement: strict
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 6443
    hubble:
      enabled: @hubbleEnabled@
      relay:
        enabled: @hubbleRelay@
      ui:
        enabled: @hubbleUI@
#     auto-direct-node-routes: true
#     direct-routing-device: @directRoutingDevice@
#     cluster-cidr: @clusterCIDR@
    gatewayAPI:
      enabled: @gatewayAPI@
    ipv4NativeRoutingCIDR: @privateCIDR@
    routingMode: native

