apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rke2-origin-ca-issuer
  namespace: kube-system
spec:
  targetNamespace: cert-manager
  createNamespace: true
  version: @version@
  chart: origin-ca-issuer
  repo: https://bhechinger.github.io/origin-ca-issuer-helm/
  valuesContent: |-
    crds:
      enabled: true
      keep: true
